service: nest-lambda

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  stage: dev
  ecr:
    images:
      nest-lambda:
        path: ./
        platform: linux/amd64

functions:
  api:
    image:
      name: nest-lambda
      command:
        - dist/serverless.handler
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          method: any
          path: /{any+}