name: Deploy Nestjs on lambda

on:
  push:
    branches:
      - KUM-67-docker-build-및-deploy
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: ${{ secrets.ECR_PATH }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: latest
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Docker image to ECR
      run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}  # Change to your desired region    
            
        
    - name: Make Environment variables
      run: |
        aws lambda update-function-configuration \
        --function-name futsal-server \
        --environment '{"Variables": {"DATABASE_TYPE": "${{ secrets.DATABASE_TYPE }}", "DATABASE_PORT": "${{ secrets.DATABASE_PORT }}", "DATABASE_HOST": "${{ secrets.DATABASE_HOST }}", "DATABASE_USERNAME": "${{ secrets.DATABASE_USERNAME }}", "DATABASE_PASSWORD": "${{ secrets.DATABASE_PASSWORD }}", "DATABASE_NAME": "${{ secrets.DATABASE_NAME }}", "JWT_ACCESS_SECRET_KEY": "${{ secrets.JWT_ACCESS_SECRET_KEY }}", "JWT_ACCESS_EXPIRATION_TIME": "${{ secrets.JWT_ACCESS_EXPIRATION_TIME }}", "JWT_REFRESH_SECRET_KEY": "${{ secrets.JWT_REFRESH_SECRET_KEY }}", "JWT_REFRESH_EXPIRATION_TIME": "${{ secrets.JWT_REFRESH_EXPIRATION_TIME }}", "CACHE_TTL": "${{ secrets.CACHE_TTL }}", "CACHE_MAX": "${{ secrets.CACHE_MAX }}", "SLACK_URL": "${{ secrets.SLACK_URL }}", "SLACK_MESSAGE_TEMPLETE": "${{ secrets.SLACK_MESSAGE_TEMPLETE }}"}}'
   
    - name: Update Lambda function image
      run: |
        aws lambda update-function-code \
          --function-name futsal-server \
          --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG